reviews:
  namespace: student48-bookinfo-prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8082
  image: ghcr.io/62130500119/bookinfo-reviews
  tag: prd
ingress:
  host: sitkmutt.bookinfo.opsta.net
  path: "/student48/reviews(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  ENABLE_RATINGS: "true"
  RATINGS_SERVICE: http://sitkmutt.bookinfo.opsta.net/student48/ratings